name: 'Change pom version'
description: 'Change pom version'
author: 'petr.steckovic@vodafone.com'
inputs:
  new-version:
    description: 'New Version'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set maven version
      run: |
        mvn versions:set -DnewVersion=${{ github.event.inputs.new-version }}
        mvn versions:commit
    - name: Validate no SNAPSHOT dependencies
      if: "! contains(github.event.inputs.new-version, 'SNAPSHOT')"
      run: |
        mvn enforcer:enforce -Drules=requireReleaseDeps
    - name: Commit version change
      run: |
        echo "Committing new version: ${{ github.event.inputs.new-version }}"
        if [[ "${{ github.event.inputs.new-version }}" == *SNAPSHOT* ]]; then
          git commit -am "[Release bot] Snapshot version bumped to ${{ github.event.inputs.new-version }}"
        else
          git commit -am "[Release bot] Release version bumped to ${{ github.event.inputs.new-version }}"
        fi