name: 'Setup Maven Build'
description: 'Setup build environment for Maven/Java'
author: 'petr.steckovic@vodafone.com'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: "Install Maven"
      run: |
        sudo sed -i 's/jammy/focal/g' /etc/apt/sources.list
        echo "update"
        sudo apt-get -o Acquire::http::Proxy="http://proxycz.oskarmobil.cz:3128" -o  Acquire::https::Proxy="http://proxycz.oskarmobil.cz:3128" update --allow-unauthenticated

        echo "install"
        sudo apt-get -o Acquire::http::Proxy="http://proxycz.oskarmobil.cz:3128" -o  Acquire::https::Proxy="http://proxycz.oskarmobil.cz:3128" install -y maven --allow-unauthenticated