name: 'Setup Maven Build'
description: 'Setup build environment for Maven/Java'
author: 'petr.steckovic@vodafone.com'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: "Install Maven"
      shell: bash
      run: |
        wget https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        tar -xvzf apache-maven-3.9.0-bin.tar.gz -C /opt
        sudo ln -s /opt/apache-maven-3.9.0 /opt/maven
        
        export M2_HOME=/opt/maven
        export MAVEN_HOME=/opt/maven
        export PATH=$PATH:/opt/maven/bin
        
        mvn -version
