name: 'Maven release'
description: 'Release maven branch'
author: 'petr.steckovic@vodafone.com'
runs:
  using: 'composite'
  steps:
    - name: Prepare release branch
      id: prepare-release-branch
      uses: stezsky/shared-actions/actions/prepare-release-branch@main
    - name: Setup Maven Build
      id: setup-maven-build
      uses: stezsky/shared-actions/actions/setup-maven-build@main
    - name: Checkout release branch
      shell: bash
      run: |
        git checkout ${{ steps.prepare-release-branch.outputs.RELEASE_BRANCH_NAME }}
    - name: Change release version
      id: change-pom-version
      uses: stezsky/shared-actions/actions/change-pom-version@main
      with:
        new-version: ${{ steps.prepare-release-branch.outputs.VERSION_NUMBER }}
#    - name: Build Release
#      id: build-release
#      uses: stezsky/shared-actions/actions/java-pipeline@main
