name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare release branch
        id: maven-release
        uses: stezsky/shared-actions/actions/maven-release@main
